
name: Build and Publish
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Quay
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and publish image to Quay
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: quay.io/ukhomeofficedigital/cicd-actions-sonarqube-housekeeping:${{ github.ref_name }}
